#!/bin/bash

build=celina2020station2

# Set credentials
export AWS_PROFILE=default


aws cloudformation list-stack-resources \
	--stack-name $build | \
	jq -r '.StackResourceSummaries[] |
		"\(.LogicalResourceId) \(.PhysicalResourceId) \(.ResourceType) \(.ResourceStatus)"
	' | column -t

echo;echo

aws cloudformation describe-stacks \
	--stack-name $build | \
	jq -r '.Stacks[0].Outputs[] |
		"\(.OutputKey) \(.OutputValue)"
	' | column -t

