#! /bin/bash

# Get DIST value from cfresultssky output
# Run !! ./cfresultssky | grep CloudFrontDistribution | awk '{print $2}'

DIST=E3HVOGXPPYPIL7

# Seperate
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/media/*"
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/media/Celinasafety*"

# Do Together
 aws cloudfront create-invalidation --distribution-id ${DIST} --paths /index.html /videomobile.html
 aws cloudfront create-invalidation --distribution-id ${DIST} --paths "/assets/*"
#aws cloudfront create-invalidation --distribution-id ${DIST} --paths /index3.html "/assets/dan/*"

